-- MySQL Script generated by MySQL Workbench
-- Lu 11 ian 2016 17:20:26 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `api` DEFAULT CHARACTER SET utf8 ;
USE `api` ;

-- -----------------------------------------------------
-- Table `api`.`CHANNELS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`CHANNELS` ;

CREATE TABLE IF NOT EXISTS `api`.`CHANNELS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'The types of developed channels: Android, IOS, Desktop etc';


-- -----------------------------------------------------
-- Table `api`.`LABELS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`LABELS` ;

CREATE TABLE IF NOT EXISTS `api`.`LABELS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_channel` INT NULL,
  `label` VARCHAR(45) NULL,
  `value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LABELS_1_idx` (`id_channel` ASC),
  CONSTRAINT `fk_LABELS_1`
    FOREIGN KEY (`id_channel`)
    REFERENCES `api`.`CHANNELS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'List of static information to be desplayed on a given channel';


-- -----------------------------------------------------
-- Table `api`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`USERS` ;

CREATE TABLE IF NOT EXISTS `api`.`USERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL COMMENT 'bcrypt password',
  `temporary_token` VARCHAR(100) NULL,
  `access_token` VARCHAR(100) NULL,
  `status` TINYINT NULL DEFAULT 1 COMMENT '0 - New, 1 - Authenticated',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'API Users table';


-- -----------------------------------------------------
-- Table `api`.`USER_SETTINGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`USER_SETTINGS` ;

CREATE TABLE IF NOT EXISTS `api`.`USER_SETTINGS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` ENUM('M', 'F') NULL DEFAULT 'M',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'API Users settings';


-- -----------------------------------------------------
-- Table `api`.`USERS_USER_SETTINGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`USERS_USER_SETTINGS` ;

CREATE TABLE IF NOT EXISTS `api`.`USERS_USER_SETTINGS` (
  `id_settings` INT NULL,
  `id_user` INT NULL,
  INDEX `index2` (`id_settings` ASC, `id_user` ASC),
  INDEX `fk_USERS_USER_SETTINGS_1_idx` (`id_user` ASC),
  CONSTRAINT `fk_USERS_USER_SETTINGS_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `api`.`USERS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USERS_USER_SETTINGS_2`
    FOREIGN KEY (`id_settings`)
    REFERENCES `api`.`USER_SETTINGS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between USERS and USER_SETTINGS';


-- -----------------------------------------------------
-- Table `api`.`COUNTRIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`COUNTRIES` ;

CREATE TABLE IF NOT EXISTS `api`.`COUNTRIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `small` VARCHAR(3) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Country table';


-- -----------------------------------------------------
-- Table `api`.`REGIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`REGIONS` ;

CREATE TABLE IF NOT EXISTS `api`.`REGIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `id_country` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_REGIONS_1_idx` (`id_country` ASC),
  CONSTRAINT `fk_REGIONS_1`
    FOREIGN KEY (`id_country`)
    REFERENCES `api`.`COUNTRIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Region table';


-- -----------------------------------------------------
-- Table `api`.`DESTINATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`DESTINATIONS` ;

CREATE TABLE IF NOT EXISTS `api`.`DESTINATIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_country` INT NULL,
  `id_region` INT NULL,
  `lat` FLOAT NULL COMMENT 'Latitude',
  `long` FLOAT NULL COMMENT 'Longitude',
  PRIMARY KEY (`id`),
  INDEX `fk_DESTINATIONS_1_idx` (`id_country` ASC),
  INDEX `fk_DESTINATIONS_2_idx` (`id_region` ASC),
  CONSTRAINT `fk_DESTINATIONS_1`
    FOREIGN KEY (`id_country`)
    REFERENCES `api`.`COUNTRIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DESTINATIONS_2`
    FOREIGN KEY (`id_region`)
    REFERENCES `api`.`REGIONS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Destination tables by country and region';


-- -----------------------------------------------------
-- Table `api`.`EVENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`EVENTS` ;

CREATE TABLE IF NOT EXISTS `api`.`EVENTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL,
  `id_destination` INT NULL,
  `departure_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `frequency` VARCHAR(45) NULL COMMENT 'DE DEZVOLTAT',
  PRIMARY KEY (`id`),
  INDEX `fk_EVENTS_1_idx` (`id_destination` ASC),
  INDEX `fk_EVENTS_2_idx` (`id_user` ASC),
  CONSTRAINT `fk_EVENTS_1`
    FOREIGN KEY (`id_destination`)
    REFERENCES `api`.`DESTINATIONS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EVENTS_2`
    FOREIGN KEY (`id_user`)
    REFERENCES `api`.`USERS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Main events table';


-- -----------------------------------------------------
-- Table `api`.`VACATION_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`VACATION_TYPES` ;

CREATE TABLE IF NOT EXISTS `api`.`VACATION_TYPES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'The types of vacation';


-- -----------------------------------------------------
-- Table `api`.`EVENTS_VACATION_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`EVENTS_VACATION_TYPES` ;

CREATE TABLE IF NOT EXISTS `api`.`EVENTS_VACATION_TYPES` (
  `id_event` INT NULL,
  `id_vacation_type` INT NULL,
  INDEX `fk_EVENTS_VACATION_TYPES_1_idx` (`id_event` ASC),
  INDEX `fk_EVENTS_VACATION_TYPES_2_idx` (`id_vacation_type` ASC),
  INDEX `index3` (`id_event` ASC, `id_vacation_type` ASC),
  CONSTRAINT `fk_EVENTS_VACATION_TYPES_1`
    FOREIGN KEY (`id_event`)
    REFERENCES `api`.`EVENTS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EVENTS_VACATION_TYPES_2`
    FOREIGN KEY (`id_vacation_type`)
    REFERENCES `api`.`VACATION_TYPES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N Link between EVENTS and VACATION_TYPES';


-- -----------------------------------------------------
-- Table `api`.`TRANSPORTATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`TRANSPORTATIONS` ;

CREATE TABLE IF NOT EXISTS `api`.`TRANSPORTATIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'The transportation types table';


-- -----------------------------------------------------
-- Table `api`.`EVENTS_TRANSPORTATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`EVENTS_TRANSPORTATIONS` ;

CREATE TABLE IF NOT EXISTS `api`.`EVENTS_TRANSPORTATIONS` (
  `id_event` INT NULL,
  `id_transportation` INT NULL,
  INDEX `index1` (`id_event` ASC, `id_transportation` ASC),
  INDEX `fk_EVENTS_TRANSPORTATIONS_2_idx` (`id_transportation` ASC),
  INDEX `index3` (`id_event` ASC),
  CONSTRAINT `fk_EVENTS_TRANSPORTATIONS_1`
    FOREIGN KEY (`id_event`)
    REFERENCES `api`.`EVENTS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EVENTS_TRANSPORTATIONS_2`
    FOREIGN KEY (`id_transportation`)
    REFERENCES `api`.`TRANSPORTATIONS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between EVENTS and TRANSPORTATIONS';


-- -----------------------------------------------------
-- Table `api`.`ACTIVITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`ACTIVITIES` ;

CREATE TABLE IF NOT EXISTS `api`.`ACTIVITIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Activities table';


-- -----------------------------------------------------
-- Table `api`.`EVENTS_ACTIVITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`EVENTS_ACTIVITIES` ;

CREATE TABLE IF NOT EXISTS `api`.`EVENTS_ACTIVITIES` (
  `id_event` INT NOT NULL,
  `id_activity` INT NOT NULL,
  INDEX `fk_EVENTS_ACTIVITIES_1_idx` (`id_activity` ASC),
  CONSTRAINT `fk_EVENTS_ACTIVITIES_1`
    FOREIGN KEY (`id_activity`)
    REFERENCES `api`.`ACTIVITIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EVENTS_ACTIVITIES_2`
    FOREIGN KEY (`id_event`)
    REFERENCES `api`.`EVENTS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between EVENTS and ACTIVITIES';


-- -----------------------------------------------------
-- Table `api`.`CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`CATEGORIES` ;

CREATE TABLE IF NOT EXISTS `api`.`CATEGORIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NULL,
  `description` VARCHAR(255) NULL,
  `icon` VARCHAR(255) NULL,
  `ord` INT NULL DEFAULT 0 COMMENT 'Order column',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Categories table';


-- -----------------------------------------------------
-- Table `api`.`ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`ITEMS` ;

CREATE TABLE IF NOT EXISTS `api`.`ITEMS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_category` INT NULL,
  `title` VARCHAR(50) NULL,
  `description` VARCHAR(255) NULL,
  `avg_weight` FLOAT NULL COMMENT 'Averege weight of the item in KG',
  `ord` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_ITEMS_1_idx` (`id_category` ASC),
  CONSTRAINT `fk_ITEMS_1`
    FOREIGN KEY (`id_category`)
    REFERENCES `api`.`CATEGORIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Items to be take in vacation';


-- -----------------------------------------------------
-- Table `api`.`EVENTS_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`EVENTS_ITEMS` ;

CREATE TABLE IF NOT EXISTS `api`.`EVENTS_ITEMS` (
  `id_event` INT NOT NULL,
  `id_item` INT NOT NULL,
  `qty` INT NULL DEFAULT 1,
  `item_status` TINYINT(1) NULL DEFAULT 0 COMMENT '0 - Not taken, 1 -  to buy, 2 -  taken\n',
  INDEX `index1` (`id_event` ASC, `id_item` ASC),
  INDEX `fk_EVENTS_ITEMS_2_idx` (`id_item` ASC),
  CONSTRAINT `fk_EVENTS_ITEMS_1`
    FOREIGN KEY (`id_event`)
    REFERENCES `api`.`EVENTS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_EVENTS_ITEMS_2`
    FOREIGN KEY (`id_item`)
    REFERENCES `api`.`ITEMS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between EVENTS and ITEMS\n';


-- -----------------------------------------------------
-- Table `api`.`ITEMS_DESTIONATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`ITEMS_DESTIONATIONS` ;

CREATE TABLE IF NOT EXISTS `api`.`ITEMS_DESTIONATIONS` (
  `id_destination` INT NOT NULL,
  `id_item` INT NOT NULL,
  INDEX `index1` (`id_destination` ASC, `id_item` ASC),
  INDEX `fk_ITEMS_DESTIONATIONS_2_idx` (`id_item` ASC),
  CONSTRAINT `fk_ITEMS_DESTIONATIONS_1`
    FOREIGN KEY (`id_destination`)
    REFERENCES `api`.`DESTINATIONS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ITEMS_DESTIONATIONS_2`
    FOREIGN KEY (`id_item`)
    REFERENCES `api`.`ITEMS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between ITEMS and DESTINATIONS';


-- -----------------------------------------------------
-- Table `api`.`ITEMS_VACATION_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`ITEMS_VACATION_TYPES` ;

CREATE TABLE IF NOT EXISTS `api`.`ITEMS_VACATION_TYPES` (
  `id_vacation_type` INT NOT NULL,
  `id_item` INT NOT NULL,
  INDEX `index1` (`id_vacation_type` ASC, `id_item` ASC),
  INDEX `fk_ITEMS_VACATION_TYPES_2_idx` (`id_item` ASC),
  CONSTRAINT `fk_ITEMS_VACATION_TYPES_1`
    FOREIGN KEY (`id_vacation_type`)
    REFERENCES `api`.`VACATION_TYPES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ITEMS_VACATION_TYPES_2`
    FOREIGN KEY (`id_item`)
    REFERENCES `api`.`ITEMS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between ITEMS and VACATION_TYPES';


-- -----------------------------------------------------
-- Table `api`.`ITEMS_TRANSPORTATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`ITEMS_TRANSPORTATIONS` ;

CREATE TABLE IF NOT EXISTS `api`.`ITEMS_TRANSPORTATIONS` (
  `id_transportation` INT NOT NULL,
  `id_item` INT NOT NULL,
  INDEX `index1` (`id_transportation` ASC, `id_item` ASC),
  INDEX `fk_ITEMS_TRANSPORTATIONS_2_idx` (`id_item` ASC),
  CONSTRAINT `fk_ITEMS_TRANSPORTATIONS_1`
    FOREIGN KEY (`id_transportation`)
    REFERENCES `api`.`TRANSPORTATIONS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ITEMS_TRANSPORTATIONS_2`
    FOREIGN KEY (`id_item`)
    REFERENCES `api`.`ITEMS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between ITEMS and TRANSPORTATIONS';


-- -----------------------------------------------------
-- Table `api`.`ITEMS_ACTIVITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `api`.`ITEMS_ACTIVITIES` ;

CREATE TABLE IF NOT EXISTS `api`.`ITEMS_ACTIVITIES` (
  `id_activity` INT NOT NULL,
  `id_item` INT NOT NULL,
  INDEX `index1` (`id_activity` ASC, `id_item` ASC),
  INDEX `fk_ITEMS_ACTIVITIES_2_idx` (`id_item` ASC),
  CONSTRAINT `fk_ITEMS_ACTIVITIES_1`
    FOREIGN KEY (`id_activity`)
    REFERENCES `api`.`ACTIVITIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ITEMS_ACTIVITIES_2`
    FOREIGN KEY (`id_item`)
    REFERENCES `api`.`ITEMS` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'N:N link table between ITEMS and ACTIVITIES';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
